
data_sources:
  "GI Buddy":
    - :GI_symptoms
  "Fitbit":
    - :steps
    - :walking
    - :running
    - :sleep
    - :weight
  "Moves":
    - :steps
    - :walking
    - :running
    - :cycling
  "Nike+ Fuelband":
    - :steps
    - :running
  "MapMyFitness":
    - :walking
    - :running
    - :cycling
  "Crohnology":
    - :GI_symptoms
  "JawBone Up":
    - :steps
  "Body Media":
    - :steps
    - :running
    - :sleep
    - :heart_rate
    - :weight
  "RunKeeper":
    - :walking
    - :running
  "FitBit Aria":
    - :weight
    - :body_fat
  "Withings":
    - :steps
    - :walking
    - :running
    - :heart_rate
    - :weight
    - :body_fat
data_source_types:
  - :steps
  - :walking
  - :running
  - :cycling
  - :sleep
  - :heart_rate
  - :weight
  - :body_fat
  - :GI_symptoms