# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.


######## THIS FILE IS SHARED OPENLY ON GITHUB. DO NOT PUT PRODUCTION SECRETS

development:
  secret_key_base: 6bc87b83efda835ad30defddff339be40dc25741e10f4f3c33cac54f19d72e3ca821a53209118c1930ba03de83637537d3b3b056098bfa2852400408cf9cf0f8

test:
  secret_key_base: c27f37cd01ba81df3d211f157097f2f836209cf19078af1bd9f25d55e7ee5521c3e280acd2bec81a1ef8e9ea999cd2f5a03dbfda3651a3c0a3cf35d018abd847




######## THIS FILE IS SHARED OPENLY ON GITHUB. DO NOT PUT PRODUCTION SECRETS


## NO SECRETS!!



# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  ### PUT NO SECRETS IN HERE
  ### NONE NO SECRETS
